version: "3.8"

services:
  nginx:
    image: nginx:1.25.3-alpine3.18
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"

  api1: &api
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    # ports:
    #   - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "75MB"
  
  api2:
    <<: *api

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "350MB"

